spd = 4;
isDead = false;
sprintSpd = 5;
timer = room_speed * 0.50; //Initializes the timer as 1 second1
gunkickx = 0;
gunkicky = 0;
w_spd = 4;
xSpeed = 0;
ySpeed = 0;
canJump = 0;
scale = abs(image_xscale);